# ParFlow sensitivity analysis - Section 3.6
# Inherits from: ../_base_bow_sensitivity.yaml

system:
  data_dir: ./data/
  code_dir: ./
domain:
  name: Bow_at_Banff_lumped_era5
  time_start: 2002-01-01 01:00
  time_end: 2009-12-31 23:00
  calibration_period: 2004-01-01, 2007-12-31
  evaluation_period: 2008-01-01, 2009-12-31
  spinup_period: 2002-01-01, 2003-12-31
  pour_point_coords: 51.1722/-115.5717
  bounding_box_coords: 51.76/-116.55/50.95/-115.5
  definition_method: lumped
  delineation:
    routing: lumped
  discretization: GRUs
  experiment_id: sensitivity_parflow
data:
  streamflow_data_provider: WSC
forcing:
  dataset: ERA5
model:
  hydrological_model: PARFLOW
  routing_model: none
optimization:
  methods:
  - sensitivity
  emulation:
    num_samples: 100
    seed: 22
    sampling_method: lhs
  metric: KGE
evaluation:
  streamflow:
    station_id: 05BB001
