# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
Ngen Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the NextGen Framework model.

This module registers Ngen-specific configuration components with the
ModelRegistry, enabling the core config system to remain model-agnostic.

PHASE 2 REFACTORING: This adapter now uses AutoGeneratedConfigAdapter
to auto-generate defaults and transformers from Pydantic Field declarations.
All defaults are maintained in NgenConfig (model_configs.py) for single
source of truth.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import NGENConfig
from symfluence.models.base import AutoGeneratedConfigAdapter, ConfigValidationError


class NgenConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for NGEN model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from NGENConfig
    Pydantic model. Only custom validation logic is implemented here.
    """

    def __init__(self, model_name: str = 'NGEN'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return NGEN Pydantic configuration schema."""
        return NGENConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate Ngen-specific configuration."""
        # Validate calibration modules have parameter lists
        modules_str = config.get('NGEN_MODULES_TO_CALIBRATE', 'CFE')
        if not modules_str:
            return

        modules = modules_str.split(',')
        for module in modules:
            module = module.strip().upper()
            param_key = f'NGEN_{module}_PARAMS_TO_CALIBRATE'
            if not config.get(param_key):
                raise ConfigValidationError(
                    f"NGEN configuration incomplete. Module '{module}' is selected for "
                    f"calibration but '{param_key}' is empty or missing."
                )

        # Validate calibration modules are a subset of selected modules
        selected_str = config.get('NGEN_MODULES_SELECTED', 'SLOTH,PET,CFE')
        selected = {m.strip().upper() for m in selected_str.split(',') if m.strip()}
        calibrate = {m.strip().upper() for m in modules_str.split(',') if m.strip()}
        not_selected = calibrate - selected
        if not_selected:
            raise ConfigValidationError(
                f"NGEN_MODULES_TO_CALIBRATE contains modules not in "
                f"NGEN_MODULES_SELECTED: {not_selected}. Add them to "
                f"NGEN_MODULES_SELECTED or remove them from NGEN_MODULES_TO_CALIBRATE."
            )


# Backward compatibility alias
NGENConfigAdapter = NgenConfigAdapter
