SYMFLUENCE_DATA_DIR: /Users/darri.eythorsson/compHydro/SYMFLUENCE_data/
SYMFLUENCE_CODE_DIR: /Users/darri.eythorsson/compHydro/SYMFLUENCE
DOMAIN_NAME: Bow_at_Banff_lumped_calibration_ensemble
POUR_POINT_COORDS: 51.1722/-115.5717
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
DOMAIN_DEFINITION_METHOD: lumped
SUB_GRID_DISCRETIZATION: lumped
DOMAIN_DISCRETIZATION: GRUs
ROUTING_DELINEATION: lumped
GEOFABRIC_TYPE: TDX
STREAM_THRESHOLD: 10000
LUMPED_WATERSHED_METHOD: TauDEM
EXPERIMENT_TIME_START: 2002-01-01 01:00
EXPERIMENT_TIME_END: 2009-12-31 23:00
CALIBRATION_PERIOD: 2004-01-01, 2007-12-31
EVALUATION_PERIOD: 2008-01-01, 2009-12-31
SPINUP_PERIOD: 2002-01-01, 2003-12-31
FORCING_DATASET: RDRS
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 2
FORCING_TIME_STEP_SIZE: 3600
STREAMFLOW_DATA_PROVIDER: WSC
STATION_ID: 05BB001
DOWNLOAD_WSC_DATA: true
OPTIMIZATION_METHODS:
- iteration
OPTIMIZATION_METRIC: KGE
TARGET_METRIC: KGE
MPI_PROCESSES: 1
FORCE_RUN_ALL_STEPS: true
SKIP_WARM_START: true
HYDROLOGICAL_MODEL: FUSE
ROUTING_MODEL: none
FUSE_SPATIAL_MODE: lumped
FUSE_WARMUP_DAYS: 730
FUSE_RUN_INTERNAL_CALIBRATION: false
FUSE_FILE_ID: calens
FUSE_EXE: fuse.exe
SETTINGS_FUSE_FILEMANAGER: fm_catch.txt
FUSE_DECISION_OPTIONS:
  RFERR:
  - multiplc_e
  ARCH1:
  - tension1_1
  ARCH2:
  - tens2pll_2
  QSURF:
  - arno_x_vic
  QPERC:
  - perc_f2sat
  ESOIL:
  - rootweight
  QINTF:
  - intflwnone
  Q_TDH:
  - rout_gamma
  SNOWM:
  - temp_index
SETTINGS_FUSE_PARAMS_TO_CALIBRATE: MAXWATR_1,MAXWATR_2,FRACTEN,RTFRAC1,PERCRTE,BASERTE,QB_POWR,TIMEDELAY,MBASE,MFMAX,MFMIN,PXTEMP,LAPSE
FUSE_PARAM_BOUNDS:
  MAXWATR_1:
  - 25
  - 500
  MAXWATR_2:
  - 50
  - 5000
  FRACTEN:
  - 0.05
  - 0.95
  RTFRAC1:
  - 0.05
  - 0.95
  PERCRTE:
  - 0.1
  - 1000.0
  BASERTE:
  - 0.001
  - 1000.0
  QB_POWR:
  - 1.0
  - 10.0
  TIMEDELAY:
  - 0.01
  - 5.0
  MBASE:
  - 0.0
  - 3.0
  MFMAX:
  - 2.0
  - 8.0
  MFMIN:
  - 0.4
  - 6.0
  PXTEMP:
  - -1.0
  - 5.0
  LAPSE:
  - -7.0
  - -4.0
FUSE_TEMPLATE_PATH: /Users/darri.eythorsson/compHydro/SYMFLUENCE_data/domain_Bow_at_Banff_lumped_calibration_ensemble/settings/FUSE/Bow_at_Banff_lumped_calibration_ensemble_calens_para_def.nc
EXPERIMENT_ID: cal_ensemble_fuse_glue
RANDOM_SEED: 42
ITERATIVE_OPTIMIZATION_ALGORITHM: GLUE
NUMBER_OF_ITERATIONS: 10
POPULATION_SIZE: 100
GLUE_THRESHOLD: 0.0
